/* AUTOGENERATED by trainer/make_gru_blob.py - do not edit.
 * Golden output replayed by the ROM's boot self-test. Must stay
 * in sync with tests/vectors/m2_expected.txt. */
#pragma once
#include <stdint.h>

static const char SELFTEST_GOLDEN[] = "HALT! WHO GOES THERE?";
static const uint32_t SELFTEST_GOLDEN_LEN = 21;
