/* AUTOGENERATED by trainer/make_ktile_h512_spike_blob.py - do not edit.
 * THROWAWAY spike model (H=512, gibberish content) -- see that
 * script's docstring and docs/spikes/rsp-matvec-ktile.md. */
#pragma once
#include <stdint.h>

static const uint32_t SELFTEST_SAMPLE_SEED = 12648430u;
static const uint16_t SELFTEST_INV_T_Q8 = 384;
static const uint16_t SELFTEST_TOP_K = 5;

static const uint32_t SELFTEST_COUNT = 1;
static const char *SELFTEST_PROMPTS[] = {""};
static const char *SELFTEST_GOLDEN[] = {"HALT! WHO GOES THERE?"};
