// Parity test for NpcService.cpp against trainer/ngpt_trainer/
// npc_service.py's prompt_fields() -- same discipline test_guard_
// instances.py used checking a Python prototype against compiled
// NPCDatabase.cpp ground truth, roles reversed: here Python (built and
// tested first, per docs/milestones/m9.md section 2) is the reference,
// and this test proves the C++ port matches it byte-for-byte. Expected
// strings below were generated by running npc_service.py's
// prompt_fields() directly -- see the git history of this file's
// introducing commit for the exact generation command.
#include "NpcService.h"
#include <cassert>
#include <cstdio>
#include <cstring>

using namespace NpcService;

static int failures = 0;

static void expect_prompt(const char *label, const Profile &profile,
                           const RelationshipState &rel, const char *mood,
                           const char *ctx, const char *ev, const char *expected)
{
  char out[128];
  uint32_t len = buildPromptFields(out, sizeof(out), profile, rel, mood, ctx, ev);
  bool ok = strcmp(out, expected) == 0 && len == strlen(expected);
  if(!ok)
  {
    printf("FAIL [%s]\n  got:      %s\n  expected: %s\n", label, out, expected);
    ++failures;
  }
  else
  {
    printf("ok   [%s] %s\n", label, out);
  }
}

// Converts Python's 0.0-1.0 relationship axes to this module's 0..1000
// fixed point -- test-only helper, matches how a real caller would scale
// a stored [0,1] float/probability into RelationshipState.
static uint16_t fx(double v) { return (uint16_t)(v * 1000.0 + 0.5); }

int main()
{
  // Selena calibration: {90,85,70,55,30} -> "sassy" (M9's core worked
  // example, docs/milestones/m9.md section 1).
  {
    Profile p{"villager", 12, Gender::Female, {90, 85, 70, 55, 30}};
    RelationshipState r{fx(1.0), fx(1.0), fx(1.0), fx(1.0), fx(0.0)};
    expect_prompt("selena calibration", p, r, "cheerful", "greeting", "",
                  "P:girl D:sassy OCC:villager R:best_friend M:cheerful C:greeting EV:none|");
  }

  // Elderly multi-word person-token, non-empty event, stranger tier.
  {
    Profile p{"healer", 70, Gender::Male, {20, 20, 20, 80, 85}};
    RelationshipState r{fx(0.0), fx(0.0), fx(0.0), fx(0.0), fx(0.5)};
    expect_prompt("elderly stranger", p, r, "worried", "farewell", "heading_home",
                  "P:elderly_man D:gruff OCC:healer R:stranger M:worried C:farewell EV:heading_home|");
  }

  // Real sampled profiles (random_npc_profile/random_relationship_state
  // in npc_service.py, seeds below), exercising occupation/descriptor/
  // tier breadth beyond the two hand-picked cases above.
  {
    Profile p{"bandit", 54, Gender::Male, {54, 35, 61, 45, 93}};
    RelationshipState r{fx(0.939), fx(0.09), fx(0.661), fx(0.797), fx(0.495)};
    expect_prompt("sampled seed=1", p, r, "sassy", "combat-banter", "",
                  "P:man D:focused OCC:bandit R:friend M:sassy C:combat-banter EV:none|");
  }
  {
    Profile p{"wizard", 60, Gender::Male, {10, 1, 43, 100, 46}};
    RelationshipState r{fx(0.083), fx(0.256), fx(0.808), fx(0.38), fx(0.901)};
    expect_prompt("sampled seed=7", p, r, "sassy", "combat-banter", "",
                  "P:elderly_man D:gruff OCC:wizard R:acquaintance M:sassy C:combat-banter EV:none|");
  }
  {
    Profile p{"villager", 33, Gender::Male, {49, 97, 70, 42, 48}};
    RelationshipState r{fx(0.282), fx(0.715), fx(0.665), fx(0.158), fx(0.831)};
    expect_prompt("sampled seed=42", p, r, "sassy", "combat-banter", "",
                  "P:man D:sassy OCC:villager R:neutral M:sassy C:combat-banter EV:none|");
  }
  {
    Profile p{"farmer", 62, Gender::Female, {13, 19, 38, 4, 81}};
    RelationshipState r{fx(0.133), fx(0.148), fx(0.675), fx(0.524), fx(0.978)};
    expect_prompt("sampled seed=1000", p, r, "sassy", "combat-banter", "",
                  "P:elderly_woman D:stoic OCC:farmer R:acquaintance M:sassy C:combat-banter EV:none|");
  }
  {
    Profile p{"merchant", 80, Gender::Male, {54, 27, 67, 60, 67}};
    RelationshipState r{fx(0.187), fx(0.686), fx(0.089), fx(0.124), fx(0.945)};
    expect_prompt("sampled seed=99999", p, r, "sassy", "combat-banter", "",
                  "P:elderly_man D:serious OCC:merchant R:acquaintance M:sassy C:combat-banter EV:none|");
  }
  {
    Profile p{"damsel", 31, Gender::Female, {13, 89, 96, 41, 28}};
    RelationshipState r{fx(0.341), fx(0.991), fx(0.638), fx(0.903), fx(0.44)};
    expect_prompt("sampled seed=0xC0FFEE", p, r, "sassy", "combat-banter", "",
                  "P:woman D:sassy OCC:damsel R:friend M:sassy C:combat-banter EV:none|");
  }
  {
    Profile p{"wizard", 7, Gender::Female, {10, 67, 62, 6, 16}};
    RelationshipState r{fx(0.775), fx(0.283), fx(0.074), fx(0.421), fx(0.982)};
    expect_prompt("sampled seed=0xDEADBEEF", p, r, "sassy", "combat-banter", "",
                  "P:girl D:anxious OCC:wizard R:acquaintance M:sassy C:combat-banter EV:none|");
  }
  {
    Profile p{"wizard", 12, Gender::Female, {63, 4, 91, 9, 54}};
    RelationshipState r{fx(0.668), fx(0.54), fx(0.45), fx(0.961), fx(0.742)};
    expect_prompt("sampled seed=55555", p, r, "sassy", "combat-banter", "",
                  "P:girl D:serious OCC:wizard R:friend M:sassy C:combat-banter EV:none|");
  }

  // Every space-separated prompt token must carry its own colon
  // (ContextBuilder's parsing convention) -- direct structural check,
  // not just string equality above.
  {
    Profile p{"noble", 70, Gender::Female, {50, 50, 50, 50, 50}};
    RelationshipState r{fx(0.5), fx(0.5), fx(0.5), fx(0.5), fx(0.5)};
    char out[128];
    buildPromptFields(out, sizeof(out), p, r, "tender", "joke", nullptr);
    char buf[128];
    strcpy(buf, out);
    char *saveptr = nullptr;
    char *tok = strtok_r(buf, " ", &saveptr);
    // strip trailing '|' from the last token before checking
    while(tok)
    {
      char *bar = strchr(tok, '|');
      if(bar) *bar = '\0';
      if(!strchr(tok, ':'))
      {
        printf("FAIL [colon-per-token] bare token: %s (full: %s)\n", tok, out);
        ++failures;
      }
      tok = strtok_r(nullptr, " ", &saveptr);
    }
    printf("ok   [colon-per-token] %s\n", out);
  }

  // OCCUPATIONS array parity spot-check against the module's own count.
  {
    int count = 0;
    for(int i = 0; i < OCCUPATION_COUNT; ++i)
      if(OCCUPATIONS[i] && OCCUPATIONS[i][0]) ++count;
    if(count != OCCUPATION_COUNT)
    {
      printf("FAIL [occupation table] expected %d populated entries, got %d\n",
             OCCUPATION_COUNT, count);
      ++failures;
    }
  }

  // M10: the archetype->Profile bridge -- any spawnInstance() output must
  // carry enough (occupation/age/gender) to feed buildPromptFields()
  // directly, so a NEW archetype (blacksmith, pub_patron, ...) doesn't
  // need its own bespoke wiring the way guard's old N: scheme did.
  {
    static const char *const TEST_NAMES[] = {"TESTNAME"};
    NPCDatabase::Archetype testArchetype{
      "tester",
      {{10, 20}, {30, 40}, {50, 60}, {70, 80}, {90, 100}},
      TEST_NAMES, 1,
      "blacksmith",     // occupation
      {30, 50},         // ageRange
    };
    NPCDatabase::NPC npc = NPCDatabase::spawnInstance(testArchetype, 0x77);

    if(strcmp(npc.occupation, "blacksmith") != 0)
    {
      printf("FAIL [archetype occupation] got %s\n", npc.occupation);
      ++failures;
    }
    if(npc.age < 30 || npc.age > 50)
    {
      printf("FAIL [archetype age range] got %d, want [30,50]\n", npc.age);
      ++failures;
    }

    Profile p = profileFor(npc);
    bool ok = strcmp(p.occupation, npc.occupation) == 0 && p.age == npc.age;
    for(int i = 0; i < NPCDatabase::TRAIT_COUNT; ++i)
      ok = ok && p.traits[i] == npc.personality[i];
    if(!ok)
    {
      printf("FAIL [profileFor] bridge mismatch\n");
      ++failures;
    }
    else
    {
      printf("ok   [profileFor] occupation=%s age=%d gender=%s\n", p.occupation,
             p.age, p.gender == Gender::Female ? "female" : "male");
    }

    /* same seed -> byte-identical bridge output, same discipline as
     * spawnInstance()'s own determinism guarantee */
    NPCDatabase::NPC npc2 = NPCDatabase::spawnInstance(testArchetype, 0x77);
    if(npc.age != npc2.age || npc.isFemale != npc2.isFemale)
    {
      printf("FAIL [archetype determinism] age/gender differ across identical seeds\n");
      ++failures;
    }
  }

  // M10: every real town archetype's occupation must be a declared
  // OCCUPATIONS entry (a typo'd occupation string would silently train
  // an unrecognized OCC: value nothing else catches), and a spawned
  // instance must round-trip through profileFor() -> buildPromptFields()
  // into a well-formed, non-degenerate prompt string.
  {
    struct Entry { const char *label; const NPCDatabase::Archetype *arch; uint32_t seed; };
    const Entry entries[] = {
      {"pub_patron", &NPCDatabase::PUB_PATRON_ARCHETYPE, 0x1234},
      {"blacksmith", &NPCDatabase::BLACKSMITH_ARCHETYPE, 0x5678},
      {"wizard",     &NPCDatabase::WIZARD_ARCHETYPE,     0x9abc},
      {"villager",   &NPCDatabase::VILLAGER_ARCHETYPE,   0xdef0},
      // M11: Briar Glen's General Store / Herbalist.
      {"merchant",   &NPCDatabase::MERCHANT_ARCHETYPE,   0x1111},
      {"healer",     &NPCDatabase::HEALER_ARCHETYPE,     0x2222},
    };
    for(const Entry &e : entries)
    {
      bool declared = false;
      for(int i = 0; i < OCCUPATION_COUNT; ++i)
        if(strcmp(OCCUPATIONS[i], e.arch->occupation) == 0) declared = true;
      if(!declared)
      {
        printf("FAIL [%s occupation] %s not in NpcService::OCCUPATIONS\n",
               e.label, e.arch->occupation);
        ++failures;
        continue;
      }

      NPCDatabase::NPC npc = NPCDatabase::spawnInstance(*e.arch, e.seed);
      Profile p = profileFor(npc);
      RelationshipState r{fx(0.5), fx(0.5), fx(0.5), fx(0.5), fx(0.0)};
      char out[128];
      uint32_t len = buildPromptFields(out, sizeof(out), p, r, "cheerful", "greeting", "");
      bool ok = len > 0 && len < sizeof(out) && strstr(out, "OCC:") != nullptr
             && strstr(out, e.arch->occupation) != nullptr;
      if(!ok)
      {
        printf("FAIL [%s prompt] malformed: %s\n", e.label, out);
        ++failures;
      }
      else
      {
        printf("ok   [%s] %s\n", e.label, out);
      }
    }
  }

  // M11: gossip hub predicate -- only the two occupations cast_corpus.py
  // actually trained on gossip EV: tags should ever receive one
  // (docs/milestones/m11.md section 2).
  {
    struct Case { const char *occ; bool want; };
    const Case cases[] = {
      {"pub_patron", true}, {"villager", true},
      {"guard", false}, {"blacksmith", false}, {"wizard", false},
      {"bandit", false}, {"innkeeper", false}, {"damsel", false},
      {nullptr, false},
    };
    for(const Case &c : cases)
    {
      bool got = isGossipHub(c.occ);
      if(got != c.want)
      {
        printf("FAIL [isGossipHub] occ=%s got=%d want=%d\n",
               c.occ ? c.occ : "(null)", got, c.want);
        ++failures;
      }
    }
    printf("ok   [isGossipHub] hub/non-hub occupations classified correctly\n");
  }

  // M11: eventFor() -- gossip wins only for a hub occupation with
  // non-empty gossip; every other combination falls back to directEvent.
  {
    struct Case
    {
      const char *label, *occ, *direct, *gossip, *want;
    };
    const Case cases[] = {
      {"hub+gossip", "pub_patron", "found_gem", "shadewrath_allied", "shadewrath_allied"},
      {"hub+no gossip", "villager", "found_gem", "", "found_gem"},
      {"hub+null gossip", "villager", "found_gem", nullptr, "found_gem"},
      {"non-hub+gossip", "guard", "found_gem", "shadewrath_allied", "found_gem"},
      {"non-hub, no direct either", "guard", "", "shadewrath_allied", ""},
      {"hub, nothing at all", "pub_patron", nullptr, nullptr, ""},
    };
    for(const Case &c : cases)
    {
      const char *got = eventFor(c.occ, c.direct, c.gossip);
      if(strcmp(got, c.want) != 0)
      {
        printf("FAIL [eventFor %s] got=%s want=%s\n", c.label, got, c.want);
        ++failures;
      }
      else
      {
        printf("ok   [eventFor %s] -> %s\n", c.label, got);
      }
    }
  }

  if(failures)
  {
    printf("\n%d FAILURE(S)\n", failures);
    return 1;
  }
  printf("\nALL OK\n");
  return 0;
}
