#!/usr/bin/env python3
"""TEMPORARY M14 portability demo blob (2026-07-29) -- NOT a production
build. Retrains the guard+engineer model fresh (same corpus/seed as
m14_portability_proof.py) via the same tested train_corpus_conditioned/
qat_finetune functions every shipped milestone uses, then writes
game/rawfs/model.bin + game/src/user/selftestGolden.h so the sci-fi
engineer archetype can be seen live, on real N64 hardware, for the
first time -- every prior verification of M14's portability proof was
host-side Python only.

Deliberately retrains rather than loading m14_portability_checkpoints/
qat.pt directly: that checkpoint captures qat_finetune's INTERMEDIATE
fake-quant parameter names (weight_ih_l0_raw etc.), and a first attempt
at manually reconstructing the post-training state (rename the _raw
suffix, skip qat_finetune's own gru._init_flat_weights() call) produced
a real SELFTEST FAIL on hardware -- safer to let the tested function do
its own cleanup than hand-reproduce internal state.

Uses M12.1's FULL shipped fix stack (lexicon-trie decode guard + min-p
shift=1), not the raw undecorated path -- this version exists to show
that M12.1's mechanism (not just the compositional conditioning scheme)
carries over to a new genre with zero code changes: invented WORDS
become structurally impossible here too, exactly like the real game,
even though the underlying sentences may still read awkwardly (this
demo's corpus is deliberately thin -- see scifi_engineer_corpus.py --
the trie fixes word-formation, not corpus density).

Does NOT touch tests/vectors/ (the real M12.1 host-test fixtures stay
untouched) -- only the two files DialogueDemo.cpp's live self-test and
interactive path actually read: game/rawfs/model.bin and
game/src/user/selftestGolden.h. BOTH FILES, PLUS THE DialogueDemo.cpp
NEW_CAST "ENGINEER" ENTRY, MUST BE REVERTED (`git checkout`) BACK TO
THE SHIPPED M12.1 STATE after this demo -- every other NPC slot reads
as garbled/wrong under this swapped model, which is expected for this
demo and not something to leave shipped.

Run (from trainer/): uv run python3 make_m14_demo_blob.py
"""
import random
import re
from pathlib import Path

from ngpt_trainer import guard_corpus as gc
from ngpt_trainer import scifi_engineer_corpus as sec
from ngpt_trainer.export import build_blob
from ngpt_trainer.model import qat_finetune, train_corpus_conditioned
from ngpt_trainer.quantize import quantize
from ngpt_trainer.ref_impl import build_word_trie, generate_sampled_trie
from ngpt_trainer.vocab import Vocab

REPO = Path(__file__).resolve().parent.parent
SEED = 0
HIDDEN = 320  # m14_portability_proof.py's own value
DEVICE = "mps"
SAMPLE_SEED = 0xC0FFEE
INV_T_Q8 = 384
TOP_K = 5
MINP_SHIFT = 1  # M12.1's shipped value (SHIFT=1, ~50% top-candidate threshold)
MAX_GOLDEN_LEN = 300  # matches make_m12_1_blob.py's own value
GOLDENS_PER_GROUP = 3
VAL_FRACTION = 0.15

_WORD_RE = re.compile(r"[A-Z']+")


def build_corpus_vocab(*texts: str) -> set[str]:
    vocab = set()
    for text in texts:
        vocab.update(_WORD_RE.findall(text.upper()))
    return vocab


def emit_selftest_header(pairs: list[tuple[str, str]]) -> str:
    def carr(name: str, items) -> str:
        vals = ", ".join(f'"{s}"' for s in items)
        return f"static const char *{name}[] = {{{vals}}};\n"

    return (
        "/* AUTOGENERATED by trainer/make_m14_demo_blob.py - do not edit.\n"
        " * TEMPORARY M14 portability demo (guard + sci-fi engineer),\n"
        " * full M12.1 fix stack (trie guard + min-p).\n"
        " * NOT the shipped M12.1 model -- revert to that after the demo. */\n"
        "#pragma once\n#include <stdint.h>\n\n"
        f"static const uint32_t SELFTEST_SAMPLE_SEED = {SAMPLE_SEED}u;\n"
        f"static const uint16_t SELFTEST_INV_T_Q8 = {INV_T_Q8};\n"
        f"static const uint16_t SELFTEST_TOP_K = {TOP_K};\n"
        f"static const uint8_t SELFTEST_MINP_SHIFT = {MINP_SHIFT};\n\n"
        f"static const uint32_t SELFTEST_COUNT = {len(pairs)};\n"
        + carr("SELFTEST_PROMPTS", [p for p, _ in pairs])
        + carr("SELFTEST_GOLDEN", [r for _, r in pairs])
    )


def held_out_split(pairs, seed, val_fraction):
    rng = random.Random(seed)
    shuffled = pairs[:]
    rng.shuffle(shuffled)
    n_val = max(1, int(len(shuffled) * val_fraction))
    return shuffled[n_val:], shuffled[:n_val]


def main():
    guard_pairs = gc.generate_pairs(seed=SEED, per_combo=3)
    engineer_pairs = sec.generate_pairs(seed=SEED, per_combo=3)
    full_text = "".join(p + r for p, r in guard_pairs + engineer_pairs)
    vocab = Vocab.from_text(full_text)
    print(f"vocab size {len(vocab)}, guard pairs {len(guard_pairs)}, "
         f"engineer pairs {len(engineer_pairs)}")

    guard_train, guard_val = held_out_split(guard_pairs, SEED, VAL_FRACTION)
    engineer_train, engineer_val = held_out_split(engineer_pairs, SEED + 1, VAL_FRACTION)
    train_pairs = guard_train + engineer_train
    val_pairs = guard_val + engineer_val

    print(f"training float phase on {DEVICE}...")
    model = train_corpus_conditioned(
        train_pairs, val_pairs, vocab, hidden=HIDDEN, seed=SEED,
        max_epochs=120, patience=12, device=DEVICE)
    print(f"float phase done: val loss {model.final_loss:.4f}")

    print("qat fine-tune...")
    model = qat_finetune(
        model, train_pairs, val_pairs, vocab, seed=SEED, lr=3e-4,
        max_epochs=30, patience=6, device=DEVICE)
    print(f"qat done: val loss {model.final_loss:.4f}")

    q = quantize(model)
    corpus_vocab = build_corpus_vocab(full_text)
    trie = build_word_trie(corpus_vocab)
    print(f"trie built: {len(corpus_vocab)} distinct words, {len(trie)} nodes")

    rng = random.Random(SAMPLE_SEED)
    guard_prompts = [p for p, _ in rng.sample(guard_pairs, GOLDENS_PER_GROUP)]
    engineer_prompts = [p for p, _ in rng.sample(engineer_pairs, GOLDENS_PER_GROUP)]

    golden_pairs = []
    print("\ngoldens (trie guard + min-p ON -- M12.1's full shipped fix stack):")
    for prompt in guard_prompts + engineer_prompts:
        # Fixed SAMPLE_SEED for every golden, NOT SAMPLE_SEED + i --
        # runSelfTestOne() in DialogueDemo.cpp replays every golden with
        # the SAME SELFTEST_SAMPLE_SEED (matching make_m12_1_blob.py's
        # own convention). A per-index seed offset here would make what
        # this script records not match what the C engine replays --
        # exactly the bug an earlier version of this script had, caught
        # by a host-side bit-exactness check before wasting another
        # Ares boot cycle on it.
        got = generate_sampled_trie(q, vocab, prompt, seed=SAMPLE_SEED,
                                    inv_t_q8=INV_T_Q8, top_k=TOP_K,
                                    max_len=MAX_GOLDEN_LEN, minp_shift=MINP_SHIFT,
                                    trie_nodes=trie)
        print(f"  {prompt}{got}")
        if not (1 <= len(got) <= MAX_GOLDEN_LEN):
            raise SystemExit(f"FATAL: degenerate golden for {prompt!r}: {got!r}")
        golden_pairs.append((prompt, got))

    blob = build_blob(q, vocab, trie_nodes=trie)
    model_bin = REPO / "game" / "rawfs" / "model.bin"
    selftest_h = REPO / "game" / "src" / "user" / "selftestGolden.h"
    model_bin.write_bytes(blob)
    selftest_h.write_text(emit_selftest_header(golden_pairs))
    print(f"\nwrote {model_bin.relative_to(REPO)} ({len(blob)} bytes)")
    print(f"wrote {selftest_h.relative_to(REPO)} ({len(golden_pairs)} goldens)")
    print("\nREMINDER: this is a TEMPORARY demo build. After verifying in Ares, "
         "revert with:\n"
         "  git checkout -- game/rawfs/model.bin game/src/user/selftestGolden.h "
         "game/src/user/DialogueDemo.cpp")


if __name__ == "__main__":
    main()
