#!/usr/bin/env python3
"""Build the M3 conditioned-GRU blob and its golden vectors.

Trains one GRU on all 12 corpus pairs, quantizes, verifies the INTEGER
reference reproduces every response from its prompt, then emits — in one
run, so nothing can drift:
  game/rawfs/model.bin            blob packed into the ROM filesystem
  tests/vectors/m3_gru.bin        identical copy, used by host tests
  tests/vectors/m3_goldens.bin    12 x (prompt, response), length-prefixed
  tests/vectors/m3_trace.bin      per-step goldens for pair 0 (after prime)
  game/src/user/selftestGolden.h  prompts+goldens+cycle tables for the ROM

Owns selftestGolden.h and game/rawfs/model.bin from M3 on (the M2 script
make_gru_blob.py now only maintains the frozen m2_* test vectors).

Run: uv run python make_m3_blob.py   (from trainer/)
"""
import struct
import sys
from pathlib import Path

from ngpt_trainer import corpus
from ngpt_trainer.export import build_blob, trace_bytes
from ngpt_trainer.model import overfit_corpus
from ngpt_trainer.quantize import quantize
from ngpt_trainer.ref_impl import generate, trace
from ngpt_trainer.vocab import Vocab

REPO = Path(__file__).resolve().parent.parent
SEED = 0


def goldens_bytes(pairs: list[tuple[str, str]]) -> bytes:
    """u16 count, then per pair: u16 len + prompt bytes, u16 len + response
    bytes. Big-endian, ASCII — parsed byte-by-byte by the C test."""
    out = struct.pack(">H", len(pairs))
    for prompt, response in pairs:
        for s in (prompt, response):
            b = s.encode("ascii")
            out += struct.pack(">H", len(b)) + b
    return out


def emit_selftest_header(pairs: list[tuple[str, str]]) -> str:
    def carr(name: str, items: tuple[str, ...] | list[str]) -> str:
        vals = ", ".join(f'"{s}"' for s in items)
        return f"static const char *{name}[] = {{{vals}}};\n"

    h = (
        "/* AUTOGENERATED by trainer/make_m3_blob.py - do not edit.\n"
        " * Prompts + golden responses replayed by the ROM boot self-test,\n"
        " * and the NPC/MOOD/EV cycle tables for the demo UI. Must stay in\n"
        " * sync with tests/vectors/m3_goldens.bin. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        f"static const uint32_t SELFTEST_COUNT = {len(pairs)};\n"
        + carr("SELFTEST_PROMPTS", [p for p, _ in pairs])
        + carr("SELFTEST_GOLDEN", [r for _, r in pairs])
        + "\n"
        + f"static const int SELFTEST_NPC_COUNT = {len(corpus.NPCS)};\n"
        + f"static const int SELFTEST_MOOD_COUNT = {len(corpus.MOODS)};\n"
        + f"static const int SELFTEST_EVENT_COUNT = {len(corpus.EVENTS)};\n"
        + carr("SELFTEST_NPCS", corpus.NPCS)
        + carr("SELFTEST_MOODS", corpus.MOODS)
        + carr("SELFTEST_EVENTS", corpus.EVENTS)
    )
    return h


def main() -> None:
    pairs = corpus.pairs()
    vocab = Vocab.from_text(corpus.corpus_text())
    q = quantize(overfit_corpus(pairs, vocab, seed=SEED))

    for prompt, response in pairs:
        got = generate(q, vocab, prompt)
        if got != response:
            print(f"FATAL: integer ref-impl for {prompt!r} generated "
                  f"{got!r}, wanted {response!r}")
            sys.exit(1)

    blob = build_blob(q, vocab)
    targets = {
        REPO / "game" / "rawfs" / "model.bin": blob,
        REPO / "tests" / "vectors" / "m3_gru.bin": blob,
        REPO / "tests" / "vectors" / "m3_goldens.bin": goldens_bytes(pairs),
        REPO / "tests" / "vectors" / "m3_trace.bin":
            trace_bytes(trace(q, vocab, pairs[0][0]), q.H),
        REPO / "game" / "src" / "user" / "selftestGolden.h":
            emit_selftest_header(pairs).encode("ascii"),
    }
    for path, data in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO)} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
