#!/usr/bin/env python3
"""THROWAWAY spike blob: H=512, right shape, gibberish content, fast.

NOT part of the project's real training pipeline (compare make_m8_blob.py,
which trains a real corpus). This exists only to hardware-verify the
K-tiling RSP kernel (docs/spikes/rsp-matvec-ktile.md) at H=512 -- the
weights just need to be THE RIGHT SHAPE and produce SOME deterministic
output, not real language. Converges on one short line (not a bare
few-step random-weight dump) specifically so the model reliably emits
EOS quickly: the ROM self-test's runXchkGeneration has a hard 2000-step
runaway guard ("no debugger on a ROM") and H=512 costs ~4x H=256 per
step, so a model that never terminates would eat a lot of boot time
before that guard even kicks in.

Run: uv run python make_ktile_h512_spike_blob.py   (from trainer/)
"""
from pathlib import Path

from ngpt_trainer.export import build_blob
from ngpt_trainer.model import overfit
from ngpt_trainer.quantize import quantize
from ngpt_trainer.ref_impl import generate, generate_sampled
from ngpt_trainer.vocab import Vocab

REPO = Path(__file__).resolve().parent.parent
CORPUS = "HALT! WHO GOES THERE?"
SEED = 0
HIDDEN = 512
SAMPLE_SEED = 0xC0FFEE
INV_T_Q8 = 384
TOP_K = 5


def emit_selftest_header(prompts, goldens) -> str:
    def esc(s):
        return s.replace("\\", "\\\\").replace('"', '\\"')
    prompts_lit = ", ".join(f'"{esc(p)}"' for p in prompts)
    goldens_lit = ", ".join(f'"{esc(g)}"' for g in goldens)
    return (
        "/* AUTOGENERATED by trainer/make_ktile_h512_spike_blob.py - do not edit.\n"
        " * THROWAWAY spike model (H=512, gibberish content) -- see that\n"
        " * script's docstring and docs/spikes/rsp-matvec-ktile.md. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "\n"
        f"static const uint32_t SELFTEST_SAMPLE_SEED = {SAMPLE_SEED}u;\n"
        f"static const uint16_t SELFTEST_INV_T_Q8 = {INV_T_Q8};\n"
        f"static const uint16_t SELFTEST_TOP_K = {TOP_K};\n"
        "\n"
        f"static const uint32_t SELFTEST_COUNT = {len(goldens)};\n"
        f"static const char *SELFTEST_PROMPTS[] = {{{prompts_lit}}};\n"
        f"static const char *SELFTEST_GOLDEN[] = {{{goldens_lit}}};\n"
    )


def main() -> None:
    vocab = Vocab.from_text(CORPUS)
    print(f"training H={HIDDEN} on a {len(CORPUS)}-char corpus (converge, not random)...")
    model = overfit(CORPUS, vocab, hidden=HIDDEN, seed=SEED)
    print(f"final_loss={model.final_loss:.6f}")
    q = quantize(model)

    got = generate(q, vocab)
    print(f"greedy check: {got!r} (want {CORPUS!r}) -- {'MATCH' if got == CORPUS else 'gibberish, fine for a spike'}")

    golden = generate_sampled(q, vocab, prompt="", seed=SAMPLE_SEED,
                               inv_t_q8=INV_T_Q8, top_k=TOP_K)
    print(f"sampled golden ({len(golden)} chars): {golden!r}")
    if len(golden) >= 250:
        print("WARNING: golden didn't hit EOS within 250 chars -- risks the "
              "ROM's 2000-step runaway guard at H=512's per-step cost. "
              "Consider more training steps or a different seed.")

    blob = build_blob(q, vocab)
    targets = {
        REPO / "game" / "rawfs" / "model.bin": blob,
        REPO / "game" / "src" / "user" / "selftestGolden.h":
            emit_selftest_header([""], [golden]).encode("ascii"),
    }
    for path, data in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO)} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
