#!/usr/bin/env python3
"""Throwaway H=320 blob for RSP-kernel bit-exactness proof ONLY -- NOT a
trained model, never meant to ship. Random deterministic int8 weights
exercise the exact same matvec arithmetic real training would (the RSP
ucode has no idea whether a byte came from gradient descent or a PRNG),
so this decouples "does the H=320 RSP kernel compute the right numbers"
from "is the H=320 corpus/training pipeline done" -- M9's own DoD keeps
these as separate checklist items on purpose (docs/milestones/m9.md
section 6's own scoping note). Text output will be gibberish; that's
expected and irrelevant to what this proves.

Writes to /tmp so it can never be mistaken for or accidentally committed
as a real model.bin. The caller (a shell driver, not this script) is
responsible for temporarily swapping it into game/rawfs/model.bin for a
ROM build + Ares boot, then restoring the real M8 model.bin afterward.

Run: uv run python make_m9_rsp_spike_blob.py   (from trainer/)
"""
import struct
from pathlib import Path

import numpy as np

from ngpt_trainer.export import build_blob, trace_bytes
from ngpt_trainer.quantize import QuantizedGRU, make_lut
from ngpt_trainer.ref_impl import generate_sampled, trace_sampled
from ngpt_trainer.vocab import Vocab

OUT_DIR = Path("/tmp/m9_rsp_spike")

HIDDEN = 320
SEED = 0xB16B00B5
SAMPLE_SEED = 0xC0FFEE
INV_T_Q8 = 384
TOP_K = 5

# Real M9 prompt schema (game/src/user/NpcService.cpp's buildPromptFields)
# -- the vocab is built to exactly cover these plus generic printable
# ASCII so any random generated response is decodable too.
PROMPTS = (
    "P:girl AGE:12 D:sassy OCC:villager R:best_friend M:cheerful C:greeting EV:none|",
    "P:elderly_man AGE:70 D:gruff OCC:healer R:stranger M:worried C:farewell EV:heading_home|",
)


def goldens_bytes(pairs: list[tuple[str, str]]) -> bytes:
    out = struct.pack(">IHHH", SAMPLE_SEED, INV_T_Q8, TOP_K, len(pairs))
    for prompt, response in pairs:
        for s in (prompt, response):
            b = s.encode("ascii")
            out += struct.pack(">H", len(b)) + b
    return out


def main():
    rng = np.random.default_rng(SEED)
    # Full printable ASCII vocab (32..126) guarantees any prompt/response
    # combination is encodable/decodable -- this blob is disposable, so
    # there's no reason to hand-tune vocab size the way a real corpus does.
    vocab_text = "".join(chr(c) for c in range(32, 127))
    vocab = Vocab.from_text(vocab_text)
    V = len(vocab)
    H = HIDDEN

    q = QuantizedGRU(
        H=H, V=V, k_w=4,
        W_ih=rng.integers(-127, 128, size=(3 * H, V), dtype=np.int8),
        W_hh=rng.integers(-127, 128, size=(3 * H, H), dtype=np.int8),
        b_ih=rng.integers(-1000, 1000, size=(3 * H,), dtype=np.int32),
        b_hh=rng.integers(-1000, 1000, size=(3 * H,), dtype=np.int32),
        k_out=4,
        W_out=rng.integers(-127, 128, size=(V, H), dtype=np.int8),
        b_out=rng.integers(-1000, 1000, size=(V,), dtype=np.int32),
        lut_sigmoid=make_lut(lambda x: 1 / (1 + np.exp(-x))),
        lut_tanh=make_lut(np.tanh),
    )

    blob = build_blob(q, vocab)
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "model.bin").write_bytes(blob)
    print(f"wrote {OUT_DIR / 'model.bin'} ({len(blob)} bytes), H={H} V={V}")

    golden_pairs = []
    for prompt in PROMPTS:
        got = generate_sampled(q, vocab, prompt, seed=SAMPLE_SEED,
                                inv_t_q8=INV_T_Q8, top_k=TOP_K)
        print(f"  {prompt}\n    -> {got!r}")
        golden_pairs.append((prompt, got))

    (OUT_DIR / "goldens.bin").write_bytes(goldens_bytes(golden_pairs))
    (OUT_DIR / "trace.bin").write_bytes(
        trace_bytes(trace_sampled(q, vocab, golden_pairs[0][0],
                                   SAMPLE_SEED, INV_T_Q8, TOP_K), q.H))
    print(f"wrote {OUT_DIR / 'goldens.bin'} and {OUT_DIR / 'trace.bin'}")

    def c_escape(s: str) -> str:
        # Random synthetic text draws from the full printable ASCII range
        # (unlike real corpora, which are curated and never hit this) --
        # backslash and double-quote must be escaped or they break the C
        # string literal.
        return s.replace("\\", "\\\\").replace('"', '\\"')

    def carr(name: str, items) -> str:
        vals = ", ".join(f'"{c_escape(s)}"' for s in items)
        return f"static const char *{name}[] = {{{vals}}};\n"

    header = (
        "/* AUTOGENERATED by trainer/make_m9_rsp_spike_blob.py - THROWAWAY,\n"
        " * random untrained weights, RSP-kernel bit-exactness proof only. */\n"
        "#pragma once\n#include <stdint.h>\n\n"
        f"static const uint32_t SELFTEST_SAMPLE_SEED = {SAMPLE_SEED}u;\n"
        f"static const uint16_t SELFTEST_INV_T_Q8 = {INV_T_Q8};\n"
        f"static const uint16_t SELFTEST_TOP_K = {TOP_K};\n\n"
        f"static const uint32_t SELFTEST_COUNT = {len(golden_pairs)};\n"
        + carr("SELFTEST_PROMPTS", [p for p, _ in golden_pairs])
        + carr("SELFTEST_GOLDEN", [r for _, r in golden_pairs])
    )
    (OUT_DIR / "selftestGolden.h").write_text(header)
    print(f"wrote {OUT_DIR / 'selftestGolden.h'}")


if __name__ == "__main__":
    main()
