#!/usr/bin/env python3
"""Build the NGPT v1 (quantized GRU) model blob and its golden vectors.

Trains the M2 one-line GRU, quantizes it, verifies the INTEGER reference
implementation reproduces the corpus, then emits — in one run, so nothing
can drift apart:
  game/rawfs/model.bin            blob packed into the ROM filesystem
  tests/vectors/m2_gru.bin        identical copy, used by host tests
  tests/vectors/m2_expected.txt   expected generation, byte-for-byte
  tests/vectors/m2_trace.bin      per-step ids + hidden states (BE)
  game/src/user/selftestGolden.h  expected text for the ROM boot self-test

Run: uv run python make_gru_blob.py   (from trainer/)
"""
import sys
from pathlib import Path

from ngpt_trainer.export import build_blob, trace_bytes
from ngpt_trainer.model import overfit
from ngpt_trainer.quantize import quantize
from ngpt_trainer.ref_impl import generate, trace
from ngpt_trainer.vocab import Vocab

REPO = Path(__file__).resolve().parent.parent
CORPUS = "HALT! WHO GOES THERE?"
SEED = 0


def emit_selftest_header(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return (
        "/* AUTOGENERATED by trainer/make_gru_blob.py - do not edit.\n"
        " * Golden output replayed by the ROM's boot self-test. Must stay\n"
        " * in sync with tests/vectors/m2_expected.txt. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "\n"
        f'static const char SELFTEST_GOLDEN[] = "{escaped}";\n'
        f"static const uint32_t SELFTEST_GOLDEN_LEN = {len(text.encode('ascii'))};\n"
    )


def main() -> None:
    vocab = Vocab.from_text(CORPUS)
    q = quantize(overfit(CORPUS, vocab, seed=SEED))

    got = generate(q, vocab)
    if got != CORPUS:
        print(f"FATAL: integer ref-impl generated {got!r}, wanted {CORPUS!r}")
        sys.exit(1)

    blob = build_blob(q, vocab)
    targets = {
        REPO / "game" / "rawfs" / "model.bin": blob,
        REPO / "tests" / "vectors" / "m2_gru.bin": blob,
        REPO / "tests" / "vectors" / "m2_expected.txt": CORPUS.encode("ascii"),
        REPO / "tests" / "vectors" / "m2_trace.bin": trace_bytes(trace(q, vocab), q.H),
        REPO / "game" / "src" / "user" / "selftestGolden.h":
            emit_selftest_header(CORPUS).encode("ascii"),
    }
    for path, data in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO)} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
