#!/usr/bin/env python3
"""Build the NGPT v0 (canned-text) model blob and its golden vectors.

This is the M1 stand-in for the real training pipeline: instead of weights,
the "model" payload is a fixed byte string that the engine replays verbatim.
It ships through the exact same loader the GRU blob will use from M2 on.

Outputs (all committed to git):
  game/rawfs/model.bin            the blob packed into the ROM filesystem
  tests/vectors/m1_canned.bin     identical copy, used by host tests
  tests/vectors/m1_expected.txt   expected generation output, byte-for-byte
  game/src/user/selftestGolden.h  same expectation, embedded in the ROM's
                                  boot self-test

Format (see docs/03-blob-format.md), all integers big-endian:
  offset  size  field
  0       4     magic "NGPT"
  4       2     format version (1)
  6       2     model type (0 = canned text)
  8       4     payload length N
  12      N     payload (canned: raw ASCII bytes of the line)

Stdlib-only on purpose: runs on any Python 3, no venv needed yet.
Usage: python3 trainer/make_canned_blob.py   (from the repo root)
"""

import struct
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

MAGIC = b"NGPT"
FORMAT_VERSION = 1
MODEL_TYPE_CANNED = 0

# The one line our fake "AI" says. Uppercase because the engine's builtin
# debug font only has uppercase glyphs (fine for the walking skeleton).
CANNED_LINE = "HALT! WHO GOES THERE?"


def build_blob(text: str) -> bytes:
    payload = text.encode("ascii")
    header = MAGIC + struct.pack(">HHI", FORMAT_VERSION, MODEL_TYPE_CANNED, len(payload))
    return header + payload


def emit_selftest_header(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return (
        "/* AUTOGENERATED by trainer/make_canned_blob.py - do not edit.\n"
        " * Golden output replayed by the ROM's boot self-test. Must stay\n"
        " * in sync with tests/vectors/m1_expected.txt. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "\n"
        f'static const char SELFTEST_GOLDEN[] = "{escaped}";\n'
        f"static const uint32_t SELFTEST_GOLDEN_LEN = {len(text.encode('ascii'))};\n"
    )


def main() -> None:
    blob = build_blob(CANNED_LINE)
    expected = CANNED_LINE.encode("ascii")

    targets = {
        REPO / "game" / "rawfs" / "model.bin": blob,
        REPO / "tests" / "vectors" / "m1_canned.bin": blob,
        REPO / "tests" / "vectors" / "m1_expected.txt": expected,
        REPO / "game" / "src" / "user" / "selftestGolden.h":
            emit_selftest_header(CANNED_LINE).encode("ascii"),
    }
    for path, data in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO)} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
