#!/usr/bin/env python3
"""Build the M4 sampled-GRU blob, golden vectors, and generated headers.

The M4 pipeline: generated corpus -> train 64GPT (H=128) with a val
split -> quantize -> ACCEPTANCE GATES -> emit everything in one run so
nothing can drift:
  game/rawfs/model.bin            blob packed into the ROM filesystem
  tests/vectors/m4_gru.bin        identical copy, used by host tests
  tests/vectors/m4_goldens.bin    sampler params + 12 x (prompt, seeded
                                  sampled response), length-prefixed
  tests/vectors/m4_trace.bin      per-step sampled goldens for pair 0
  game/src/user/selftestGolden.h  prompts+goldens+params+cycle tables
  core/ngpt_sampler_lut.h         exp2 LUT, twin of sampler_lut.py

Acceptance gates (plan.md M4): int8-vs-float top-1 agreement >= 95% on
held-out sequences, and every seeded golden non-empty. Val loss is
printed for the record in docs/milestones/m4.md.

Training is cached in trainer/.m4_model.pt (git-ignored); delete it to
retrain. Owns selftestGolden.h and game/rawfs/model.bin from M4 on.

Run: uv run python make_m4_blob.py   (from trainer/)
"""
import struct
import sys
from pathlib import Path

import numpy as np
import torch

from ngpt_trainer import corpus
from ngpt_trainer.corpus_gen import generate_pairs, corpus_text
from ngpt_trainer.export import build_blob, trace_bytes
from ngpt_trainer.model import CharGRU, one_hot, train_corpus
from ngpt_trainer.quantize import quantize
from ngpt_trainer.ref_impl import generate_sampled, gru_step, trace_sampled
from ngpt_trainer.sampler_lut import LUT_EXP2
from ngpt_trainer.vocab import Vocab

REPO = Path(__file__).resolve().parent.parent
CACHE = Path(__file__).resolve().parent / ".m4_model.pt"

SEED = 0
HIDDEN = 128
# Self-test sampling config — pinned by the goldens; the demo may reseed
# freely at runtime, the self-test replays exactly these.
SAMPLE_SEED = 0xC0FFEE
INV_T_Q8 = 384  # T = 2/3 (base-2; chosen over 320 after the eyeball gate
                # showed two derailed lines at the hotter setting)
TOP_K = 5
MIN_AGREEMENT = 0.95


def get_model(pairs, vocab) -> CharGRU:
    if CACHE.exists():
        d = torch.load(CACHE, weights_only=True)
        model = CharGRU(vocab_size=len(vocab), hidden=d["hidden"])
        model.load_state_dict(d["state"])
        model.eval()
        model.final_loss = d["val_loss"]
        print(f"loaded cached model (val loss {model.final_loss:.4f})")
        return model
    model = train_corpus(pairs, vocab, hidden=HIDDEN, seed=SEED)
    torch.save({"state": model.state_dict(), "val_loss": model.final_loss,
                "hidden": HIDDEN}, CACHE)
    return model


def top1_agreement(model, q, vocab, probe: list[list[int]]) -> float:
    """Teacher-forced float-vs-int argmax agreement over probe sequences:
    both sides consume the same EOS+ids stream; compare their next-token
    argmax at every position."""
    match = total = 0
    with torch.no_grad():
        for ids in probe:
            flogits, _ = model(one_hot([vocab.eos_id] + ids, len(vocab)))
            fam = torch.argmax(flogits[0], dim=-1).tolist()
            h = np.zeros(q.H, dtype=np.int64)
            for pos, x in enumerate([vocab.eos_id] + ids):
                h, logits = gru_step(q, h, x)
                match += int(np.argmax(logits)) == fam[pos]
                total += 1
    return match / total


def goldens_bytes(pairs: list[tuple[str, str]]) -> bytes:
    """u32 sample seed, u16 inv_t_q8, u16 top_k, u16 count, then per
    pair: u16 len + prompt bytes, u16 len + response bytes. Big-endian,
    parsed byte-by-byte by the C test."""
    out = struct.pack(">IHHH", SAMPLE_SEED, INV_T_Q8, TOP_K, len(pairs))
    for prompt, response in pairs:
        for s in (prompt, response):
            b = s.encode("ascii")
            out += struct.pack(">H", len(b)) + b
    return out


def emit_sampler_lut_header() -> str:
    rows = []
    for i in range(0, 256, 12):
        rows.append("  " + ", ".join(str(v) for v in LUT_EXP2[i:i + 12]) + ",")
    return (
        "/* AUTOGENERATED by trainer/make_m4_blob.py - do not edit.\n"
        " * exp2 LUT over [-16, 0) in Q10 (64-unit buckets), values Q15.\n"
        " * Twin of ngpt_trainer/sampler_lut.py - one source, no drift. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "static const uint16_t NGPT_LUT_EXP2[256] = {\n"
        + "\n".join(rows) + "\n};\n"
    )


def emit_selftest_header(pairs: list[tuple[str, str]]) -> str:
    def carr(name: str, items) -> str:
        vals = ", ".join(f'"{s}"' for s in items)
        return f"static const char *{name}[] = {{{vals}}};\n"

    return (
        "/* AUTOGENERATED by trainer/make_m4_blob.py - do not edit.\n"
        " * Prompts + SEEDED SAMPLED golden responses replayed by the ROM\n"
        " * boot self-test (ngpt_set_sampler with the params below), and\n"
        " * the NPC/MOOD/EV cycle tables for the demo UI. Must stay in\n"
        " * sync with tests/vectors/m4_goldens.bin. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        f"static const uint32_t SELFTEST_SAMPLE_SEED = {SAMPLE_SEED}u;\n"
        f"static const uint16_t SELFTEST_INV_T_Q8 = {INV_T_Q8};\n"
        f"static const uint16_t SELFTEST_TOP_K = {TOP_K};\n\n"
        f"static const uint32_t SELFTEST_COUNT = {len(pairs)};\n"
        + carr("SELFTEST_PROMPTS", [p for p, _ in pairs])
        + carr("SELFTEST_GOLDEN", [r for _, r in pairs])
        + "\n"
        + f"static const int SELFTEST_NPC_COUNT = {len(corpus.NPCS)};\n"
        + f"static const int SELFTEST_MOOD_COUNT = {len(corpus.MOODS)};\n"
        + f"static const int SELFTEST_EVENT_COUNT = {len(corpus.EVENTS)};\n"
        + carr("SELFTEST_NPCS", corpus.NPCS)
        + carr("SELFTEST_MOODS", corpus.MOODS)
        + carr("SELFTEST_EVENTS", corpus.EVENTS)
    )


def main() -> None:
    pairs = generate_pairs(seed=SEED)
    vocab = Vocab.from_text(corpus_text(seed=SEED))
    model = get_model(pairs, vocab)
    q = quantize(model)

    # gate 1: int8 faithfully reproduces the float model's decisions
    encoded = [vocab.encode(p) + vocab.encode(r) for p, r in pairs]
    agree = top1_agreement(model, q, vocab, encoded[9::10][:120])
    print(f"val loss {model.final_loss:.4f}; int-vs-float top-1 {agree:.4f}")
    if agree < MIN_AGREEMENT:
        print(f"FATAL: agreement {agree:.4f} < {MIN_AGREEMENT}")
        sys.exit(1)

    # gate 2: seeded sampled goldens, one per condition (+ the eyeball)
    prompt_list = [corpus.prompt_for(n, m, e) for n in corpus.NPCS
                   for m in corpus.MOODS for e in corpus.EVENTS]
    golden_pairs = []
    for prompt in prompt_list:
        got = generate_sampled(q, vocab, prompt, seed=SAMPLE_SEED,
                               inv_t_q8=INV_T_Q8, top_k=TOP_K)
        print(f"  {prompt}{got}")
        if not (1 <= len(got) <= 200):
            print(f"FATAL: degenerate golden for {prompt!r}: {got!r}")
            sys.exit(1)
        golden_pairs.append((prompt, got))

    blob = build_blob(q, vocab)
    targets = {
        REPO / "game" / "rawfs" / "model.bin": blob,
        REPO / "tests" / "vectors" / "m4_gru.bin": blob,
        REPO / "tests" / "vectors" / "m4_goldens.bin":
            goldens_bytes(golden_pairs),
        REPO / "tests" / "vectors" / "m4_trace.bin":
            trace_bytes(trace_sampled(q, vocab, golden_pairs[0][0],
                                      SAMPLE_SEED, INV_T_Q8, TOP_K), q.H),
        REPO / "game" / "src" / "user" / "selftestGolden.h":
            emit_selftest_header(golden_pairs).encode("ascii"),
        REPO / "core" / "ngpt_sampler_lut.h":
            emit_sampler_lut_header().encode("ascii"),
    }
    for path, data in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO)} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
